print('\033[1;34mXoá Tất Cả Các Tệp')
def my_funcion() :
    print('* Variable 1')
    a=b=c=d="Đã Xoá Thành Công"
    print(a)
    print(b)
    print(c)
    print(d)
    print(" ")
    print('* Variable 2')
    a=b=c=d="Đã Xoá Thành Công"
    print(a)
    print(b)
    print(c)
    print(d)
    print(" ")
    print('* Variable 3')
    a=b=c=d="Đã Xoá Thành Công"
    print(a)
    print(b)
    print(c)
    print(d)
    print(" ")
    print('* Variable 4')
    a=b=c=d="Đã Xoá Thành Công"
    print(a)
    print(b)
    print(c)
    print(d)
my_funcion()
